- hosts: zvm2

  collections:
    - ibm.ibm_zos_core

  gather_facts: no

  environment: "{{ environment_vars }}"
  vars_files: 
    - "host_vars/cicd_artifacts.yml"

  tasks:

    #delete generated dbds
    - name: clear dbdlib
      zos_data_set:
        #name: IMSTESTU.ANSI.DBDLIB2({{ item }})
        name: '{{ target_dbdlib }}({{ item }})'
        state: absent
        type: MEMBER
      loop: '{{ dbds }}'

    #Delete generates psbs
    - name: clear psblib
      zos_data_set:
        #name: IMSTESTU.ANSI.PSBLIB2({{ item }})
        name: '{{ target_psblib }}({{ item }})'
        state: absent
        type: MEMBER
      loop: '{{ psbs }}'

    #Delete generates acbs
    - name: clear acblib
      zos_data_set:
        #name: IMSTESTU.ANSI.ACBLIB1({{ item }})
        name: '{{ target_acblib }}({{ item }})'
        state: absent
        type: MEMBER
      loop: '{{ acbs }}'